import type { Metadata } from "next";

import { Box } from "@mui/material";

import { AppThemeProvider } from "@/theme/themeProvider";
import { Navbar } from "@/components/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppThemeProvider>
      <html lang="en">
        <body>
          <Navbar />
          <main>
            <Box sx={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              minHeight: 'calc(100vh - 4rem)',
              marginTop: '4rem',
            }}>
              {children}
            </Box>
          </main>
        </body>
      </html>
    </AppThemeProvider>
  );
}
